server:
  port: 8081
  
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/studynote?characterEncoding=utf8
    username: study
    password: study
    driver-class-name: com.mysql.cj.jdbc.Driver
