server:
  port: 8081
  
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:15025/studynote?characterEncoding=utf8
    username: studynote
    password: studynote
    driver-class-name: com.mysql.cj.jdbc.Driver
